pygments: true

title : KholdCode
tagline: Site Tagline
author :
  name : Alexander Kondratskiy
  email : kholdstare0.0@gmail.com
  github : KholdStare

production_url : http://kholdstare.github.com

exclude:
  - sass
  - icomoonFonts
