pygments: true

title: KholdCode
tagline: Site Tagline
author :
  name: Alexander Kondratskiy
  email: kholdstare0.0@gmail.com
  github: "KholdStare"

production_url : http://kholdstare.github.com
markdown: kramdown

nav_locations:
  - url: "/index.html"
    name: Home
    icon: home
  - url: "/about.html"
    name: About
    icon: info
  - url: "http://feeds.feedburner.com/Kholdcode"
    name: Subscribe
    icon: feed

exclude:
  - sass
  - icomoonFonts
  - diagrams_src
  - javascripts/foundation/join.bash
